<?php  exit();
/*
Page: /index.php?upcache=1
Error: Unknown column 'typenameen' in 'field list' <br />Error sql: <font color='red'>SELECT id,typename,typenameen,typedir,typeimg,description,isdefault,ispart,defaultname,namerule2,moresite,siteurl,sitepath 
                          FROM `dede_arctype` WHERE id='3' LIMIT 0,1;</font>
Time2018-11-18 10:13:01
*/
?>
<?php  exit();
/*
Page: /index.php?upcache=1
Error: Unknown column 'typenameen' in 'field list' <br />Error sql: <font color='red'>SELECT id,typename,typenameen,typedir,typeimg,description,isdefault,ispart,defaultname,namerule2,moresite,siteurl,sitepath 
                          FROM `dede_arctype` WHERE id='3' LIMIT 0,1;</font>
Time2018-11-18 10:13:01
*/
?>
<?php  exit();
/*
Page: /index.php?upcache=1
Error: Unknown column 'typenameen' in 'field list' <br />Error sql: <font color='red'>SELECT id,typename,typenameen,typedir,typeimg,description,isdefault,ispart,defaultname,namerule2,moresite,siteurl,sitepath 
                          FROM `dede_arctype` WHERE id='1' LIMIT 0,1;</font>
Time2018-11-18 10:13:01
*/
?>
<?php  exit();
/*
Page: /index.php?upcache=1
Error: Unknown column 'typenameen' in 'field list' <br />Error sql: <font color='red'>SELECT id,typename,typenameen,typedir,typeimg,description,isdefault,ispart,defaultname,namerule2,moresite,siteurl,sitepath 
                          FROM `dede_arctype` WHERE id='1' LIMIT 0,1;</font>
Time2018-11-18 10:13:01
*/
?>
<?php  exit();
/*
Page: /index.php?upcache=1
Error: Unknown column 'typenameen' in 'field list' <br />Error sql: <font color='red'>SELECT id,typename,typenameen,typedir,typeimg,description,isdefault,ispart,defaultname,namerule2,moresite,siteurl,sitepath 
                          FROM `dede_arctype` WHERE id='1' LIMIT 0,1;</font>
Time2018-11-18 10:13:01
*/
?>
<?php  exit();
/*
Page: /index.php?upcache=1
Error: Unknown column 'typenameen' in 'field list' <br />Error sql: <font color='red'>SELECT id,typename,typenameen,typedir,typeimg,description,isdefault,ispart,defaultname,namerule2,moresite,siteurl,sitepath 
                          FROM `dede_arctype` WHERE id='9' LIMIT 0,1;</font>
Time2018-11-18 10:13:01
*/
?>
<?php  exit();
/*
Page: /index.php?upcache=1
Error: Unknown column 'typenameen' in 'field list' <br />Error sql: <font color='red'>SELECT id,typename,typenameen,typedir,typeimg,description,isdefault,ispart,defaultname,namerule2,moresite,siteurl,sitepath 
                          FROM `dede_arctype` WHERE id='9' LIMIT 0,1;</font>
Time2018-11-18 10:13:01
*/
?>
<?php  exit();
/*
Page: /index.php?upcache=1
Error: Unknown column 'typenameen' in 'field list' <br />Error sql: <font color='red'>SELECT id,typename,typenameen,typedir,typeimg,description,isdefault,ispart,defaultname,namerule2,moresite,siteurl,sitepath 
                          FROM `dede_arctype` WHERE id='2' LIMIT 0,1;</font>
Time2018-11-18 10:13:01
*/
?>
