<?php
$z[0]=Array("arcurl","",31,46);
$z[0][4]=array();
$z[1]=Array("title","",55,69);
$z[1][4]=array();
$z[2]=Array("pubdate","",148,191);
$z[2][4]=array();
$z[2][4]['function']="MyDate('d',@me)";
$z[3]=Array("pubdate","",237,282);
$z[3][4]=array();
$z[3][4]['function']="MyDate('Y/m',@me)";
$z[4]=Array("title","",366,380);
$z[4][4]=array();
$z[5]=Array("description","",407,457);
$z[5][4]=array();
$z[5][4]['function']="cn_substr(@me,200)";

?>