<li class="xl12 xs12 xm6 xb6 padding-big news-item2"> <a href="[field:arcurl/]" title="[field:title/]">
            <div class="news-tit ">
              <div class="float-left news-span1">
                <div class="news-time">
                  <div class="news-time-date"> <span>[field:pubdate function="MyDate('m',@me)"/]</span>/<span>[field:pubdate function="MyDate('d',@me)"/]</span> </div>
                  <div class="news-time-year">[field:pubdate function="MyDate('Y',@me)"/]</div>
                </div>
              </div>
              <div class="float-left news-span2">
                <div class="news-action ">
                  <p class=" news-title ">[field:title/]</p>
                  <p class="news-desc ">[field:description function="cn_substr(@me,80)"/]...</p>
                </div>
              </div>
            </div>
            </a> </li>