<?php
$z[0]=Array("channel","\r\n<a href='[field:typeurl/]' style=\"color: rgb(187, 187, 187);\">[field:typename/]</a>|\r\n",444,623);
$z[0][4]=array();
$z[0][4]['type']="top";
$z[0][4]['currentstyle']="<a href='~typelink~'>~typename~</a>";
$z[1]=Array("global","",729,753);
$z[1][4]=array();
$z[1][4]['name']="mingcheng";
$z[2]=Array("global","",1141,1165);
$z[2][4]=array();
$z[2][4]['name']="lianxiren";
$z[3]=Array("global","",1177,1199);
$z[3][4]=array();
$z[3][4]['name']="dianhua";
$z[4]=Array("global","",1215,1235);
$z[4][4]=array();
$z[4][4]['name']="dizhi";
$z[5]=Array("global","",1292,1318);
$z[5][4]=array();
$z[5][4]['name']="cfg_powerby";

?>