<?php
$z[0]=Array("flink","  [field:link /]    ",114,196);
$z[0][4]=array();
$z[0][4]['titlelen']="20";
$z[0][4]['row']="20";
$z[0][4]['type']="text";
$z[1]=Array("global","",464,485);
$z[1][4]=array();
$z[1][4]['name']="cfg_qq";
$z[2]=Array("global","",558,579);
$z[2][4]=array();
$z[2][4]['name']="cfg_dh";
$z[3]=Array("global","",612,633);
$z[3][4]=array();
$z[3][4]['name']="cfg_yx";
$z[4]=Array("global","",664,685);
$z[4][4]=array();
$z[4][4]['name']="cfg_dz";
$z[5]=Array("sql"," \r\n        \r\n        [field:content  function='cn_substr(html2text(@me),300)'/]...\r\n        \r\n        ",700,873);
$z[5][4]=array();
$z[5][4]['sql']="Select content from dede_arctype where id=1";
$z[6]=Array("global","",1203,1229);
$z[6][4]=array();
$z[6][4]['name']="cfg_powerby";
$z[7]=Array("global","",1352,1376);
$z[7][4]=array();
$z[7][4]['name']="cfg_beian";

?>