<?php
$z[0]=Array("flink","  [field:link /] &nbsp;&nbsp; ",114,204);
$z[0][4]=array();
$z[0][4]['titlelen']="20";
$z[0][4]['row']="20";
$z[0][4]['type']="text";
$z[1]=Array("global","",476,497);
$z[1][4]=array();
$z[1][4]['name']="cfg_qq";
$z[2]=Array("global","",590,611);
$z[2][4]=array();
$z[2][4]['name']="cfg_dh";
$z[3]=Array("global","",660,681);
$z[3][4]=array();
$z[3][4]['name']="cfg_yx";
$z[4]=Array("global","",712,733);
$z[4][4]=array();
$z[4][4]['name']="cfg_dz";
$z[5]=Array("sql"," \r\n        \r\n        [field:content  function='cn_substr(html2text(@me),300)'/]...\r\n        \r\n        ",748,921);
$z[5][4]=array();
$z[5][4]['sql']="Select content from dede_arctype where id=1";
$z[6]=Array("global","",1251,1277);
$z[6][4]=array();
$z[6][4]['name']="cfg_powerby";
$z[7]=Array("global","",1419,1443);
$z[7][4]=array();
$z[7][4]['name']="cfg_beian";

?>